libxml2: Autospec creation for update from version 2.14.3 to version 2.14.4
Nick Wellnhofer (13):
      Revert "meson: Install libxml2.py"
      reader: Fix null deref on malloc failure
      io: Make xmlOutputBufferCreate* not free encoder on error
      parser: Undeprecate some parser context members
      cmake: Make iconv a private dependency
      cmake: Avoid overlinking with non-CMake libxml2-config.cmake
      parser: Only validate EnumerationTypes when requested
      parser: Use parser context as default in resource loader
      tree: Fix integer overflow in xmlBuildQName
      error: Fix initGenericErrorDefaultFunc compatibility macro again
      parser: Fix custom SAX parsers without cdataBlock handler
      parser: Fix parsing of PublicIds and VersionNums
      Release v2.14.4

v2.14.4: Jun 16 2025

### Regressions

- parser: Fix parsing of PublicIds and VersionNums
- parser: Fix custom SAX parsers without cdataBlock handler
- error: Fix initGenericErrorDefaultFunc compatibility macro again
- io: Make xmlOutputBufferCreate* not free encoder on error
- reader: Fix null deref on malloc failure
- Revert "meson: Install libxml2.py"

### Security

- tree: Fix integer overflow in xmlBuildQName

(NEWS truncated at 15 lines)